
!ScratchViewerMorph class methodsFor: 'class initialization' stamp: 'EMP 7/13/2017 18:34'!
initialize
	"self initialize"

	CatList := #(
		"Category		R		G		B"
		('Motion'		74		108	212)
		('Events'		200	131	48)
		('Looks'			138	85		215)
		('Control'		225	169	26)
		('Sound'		187	66		195)
		('Sensing'		44		165	226)
		('Pen'			14		154	108)
		('Operators'		92		183	18)
		('Data'			238	125	22)
		('More Blocks'	99		45		153)
	).! !
